sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

language: node_js
node_js:
  - 7
  - 6

services:
  - docker

cache: yarn

before_install:
  - docker-compose up -d

install:
  - yarn install

script:
  - npm test

notifications:
  email: false