version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: json2mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: demo
